pgpool:
 build: ./pgpool
 container_name: pgpool
 ports:
  - "9999:9999"
 links:
  - db1
  - db2
  - server
db1:
 build: ./postgis
 container_name: postgis1
 ports:
  - "5433:5432"
 volumes:
  - ~/postgres_data:/var/lib/postgresql
db2:
 build: ./postgis
 container_name: postgis2
 ports:
  - "5434:5432"
 volumes:
  - ~/postgres_data:/var/lib/postgresql
server:
 build: ./geoserver
 container_name: geoserver
 ports:
  - "8080:8080"
