pgpool:
 build: ./pgpool
 container_name: pgpool
 ports:
  - "9999:9999"
 links:
  - server
 volumes:
  - ~/postgres_data:/var/lib/postgresql
server:
 build: ./geoserver
 container_name: geoserver
 ports:
  - "8080:8080"
